### PR TITLE
ENG-34124 Remove raygun report

### PR DESCRIPTION
**Pull request by tiennguyenskedulo**
Raygun has been deprecated and is no longer in use.

### CODE REVIEW

**Review by steveneighbour — COMMENTED** [review]
raygun is still in use from what i understand but i;'m assuming this means that nothing deployed via ansible is in raygun any more?

**Comment by tiennguyenskedulo** [comment]
@steveneighbour According to this ticket, we no longer want to report anything to raygun anymore? https://skedulo.atlassian.net/browse/ENG-29390

**Comment by tiennguyenskedulo** [comment]
Now that you said it is still in use I am not really sure if we want to remove the step to report to raygun or fix it.

**Comment by willthames** [comment]
@steveneighbour this PR only changes the reporting of deployments to raygun (so that it no longer happens)

**Review by willthames — APPROVED** [review]

**Comment by steveneighbour** [comment]
> @steveneighbour this PR only changes the reporting of deployments to raygun (so that it no longer happens)

yep am aware, which is why i raised the question.  Apps like [condenser](https://app.raygun.com/dashboard/llv7f9/deployments) still report stats into Rayrun and that app is deployed via ansible.

**Comment by willthames** [comment]
This specific change only changes whether the action of a deployment taking place is reported to raygun

It has no influence on whether the application is configured to talk to raygun

**Comment by steveneighbour** [comment]
yes, am still aware of that. Deployment tracking in raygun is now broken for ALL apps, eg Condenser.

image

I doubt they care but still. I've posted comms in slack to at least give a heads up, in case anyone uses that long standing feature for something.

**Pull request merged**
